In [1]:
import torch
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [5]:
scaler.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [12]:
matrix = torch.tensor([[4,2],
                     [6,7]])
matrix.dim()

2

In [15]:
matrix.item

<function Tensor.item>

In [16]:
tensor = torch.tensor([[[3,4,5],
                       [5,6,7],
                       [7,8,9]]])
tensor.shape

torch.Size([1, 3, 3])

In [17]:
tensor.shape

torch.Size([1, 3, 3])

In [18]:
new = torch.tensor([[[[[4,5,6],
                      [6,7,8],
                      [3,5,7]]]]])
new.shape

torch.Size([1, 1, 1, 3, 3])

In [25]:
tensor = torch.rand(1,1,5,6)
tensor

tensor([[[[0.2099, 0.3719, 0.4142, 0.8892, 0.8611, 0.1576],
          [0.7002, 0.9807, 0.9474, 0.2674, 0.8701, 0.0257],
          [0.8526, 0.4171, 0.0558, 0.7216, 0.7160, 0.8603],
          [0.2228, 0.0882, 0.0569, 0.2005, 0.7848, 0.5657],
          [0.4228, 0.8348, 0.6239, 0.8368, 0.1464, 0.2389]]]])

In [26]:
tensor.ndim

4

In [27]:
image = torch.rand(size =(33,33,3))
image.shape,image.ndim


(torch.Size([33, 33, 3]), 3)

In [32]:
one_ten=torch.arange(1,10,2)

In [34]:
zeroes = torch.zeros_like(one_ten)
zeroes

tensor([0, 0, 0, 0, 0])

In [36]:
torch.matmul(torch.rand(3,4),torch.rand(4,6))

tensor([[1.2792, 1.5413, 0.9997, 0.7467, 1.6069, 2.0801],
        [1.1781, 1.4076, 1.0779, 0.8065, 1.6352, 1.9345],
        [0.9566, 1.0889, 0.7282, 0.3620, 1.2618, 1.4310]])

In [40]:
tensor_A = torch.tensor([[5,6],
                       [5,3],
                       [8,9]])
tensor_A.shape

torch.Size([3, 2])

In [42]:
tensor = torch.arange(0,91,10)
tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [45]:
torch.mean(tensor.type(torch.float32))

tensor(45.)

In [4]:
import torch 
a = torch.ones((2,2),requires_grad=True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [9]:
b = torch.ones((2,2))
torch.div(a,b)

tensor([[1., 1.],
        [1., 1.]], grad_fn=<DivBackward0>)

In [2]:
arr = [[3,4],[6,7]]
print(arr)

[[3, 4], [6, 7]]


In [3]:
import numpy as np
np.array(arr)

array([[3, 4],
       [6, 7]])

In [4]:
import torch 
torch.Tensor(arr)

tensor([[3., 4.],
        [6., 7.]])

In [7]:
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [12]:
torch.rand(2,2)

tensor([[0.3245, 0.2269],
        [0.8057, 0.2161]])

In [13]:
torch.manual_seed(2)
torch.rand(2,2)

tensor([[0.6147, 0.3810],
        [0.6371, 0.4745]])

In [14]:
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

In [17]:
np.array = np.ones((2,2))
np.array

array([[1., 1.],
       [1., 1.]])

In [19]:
torch_tensor = torch.from_numpy(np.array)
torch_tensor

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [20]:
print(type(torch_tensor))

<class 'torch.Tensor'>


In [22]:
# CPU to GPU
tensor_cpu = torch.ones(2, 2)
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
tensor_cpu.to(device)

tensor([[1., 1.],
        [1., 1.]])

Note: you may need to restart the kernel to use updated packages.


In [3]:
import torch
import numpy 
import pandas 
import matplotlib.pyplot as plt

In [4]:
print(torch.__version__)

2.0.1+cpu


In [5]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [6]:
scaler.ndim

0

In [7]:
scaler.ndimension

<function Tensor.ndimension>

In [8]:
scaler.item()

7

In [9]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
matrix = torch.tensor([[[7,8],[6,5]]])
matrix

tensor([[[7, 8],
         [6, 5]]])

In [13]:
matrix.ndim

3

In [14]:
matrix.shape

torch.Size([1, 2, 2])

In [15]:
tensor = torch.tensor([[[1,2,3],[5,6,7],[7,8,9]]])
tensor.shape

torch.Size([1, 3, 3])

In [16]:
tensor = torch.tensor([[[1,2,3],[5,6,7],[8,9,5]]])
tensor

tensor([[[1, 2, 3],
         [5, 6, 7],
         [8, 9, 5]]])

In [17]:
tensor.shape

torch.Size([1, 3, 3])

In [18]:
tensor.ndim

3

In [19]:
tensor[0]

tensor([[1, 2, 3],
        [5, 6, 7],
        [8, 9, 5]])

In [20]:
random_tensor = torch.rand (1,3,4)
random_tensor

tensor([[[0.0511, 0.5605, 0.3619, 0.8482],
         [0.1820, 0.8400, 0.4006, 0.8138],
         [0.1111, 0.9363, 0.4080, 0.9350]]])

In [112]:
random_tensor.ndim

3

In [113]:
random_image_size_tensor = torch.rand(size = (224,224,3))

In [114]:
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [115]:
random_tensor = torch.rand(size = (3,4))

In [116]:
random_tensor

tensor([[0.9976, 0.2214, 0.2522, 0.9517],
        [0.6866, 0.3051, 0.3386, 0.7021],
        [0.1738, 0.6058, 0.5330, 0.9544]])

In [117]:
random_tensor.shape

torch.Size([3, 4])

In [118]:
random_tensor.ndim

2

In [119]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [120]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [121]:
random_tensor.dtype

torch.float32

In [122]:
zeros.dtype

torch.float32

In [127]:
zeros = torch.zeros(size = (4,5,1))
zeros.ndim

3

In [128]:
ones =torch.ones(1,5,2)
ones.ndim

3

In [129]:
one_to_ten = torch.arange(1,11,2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [130]:
ten_Zeros = torch.zeros_like(one_to_ten)
ten_Zeros

tensor([0, 0, 0, 0, 0])

# Tensor datatypes

In [131]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [132]:
float_32_tensor.dtype

torch.float32

In [133]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=torch.float16)
float_32_tensor.dtype

torch.float16

In [134]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None,device =None,requires_grad = False)
float_32_tensor

tensor([3., 6., 9.])

In [135]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [136]:
float_16_tensor * float_16_tensor 

tensor([ 9., 36., 81.], dtype=torch.float16)

In [137]:
x =float_16_tensor * float_32_tensor

In [138]:
x.dtype

torch.float32

In [139]:
x

tensor([ 9., 36., 81.])

In [140]:
int_32_tensor = torch.tensor([3,6,9],dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [141]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [21]:
some_torch = torch.rand(3,4)
some_torch

tensor([[0.5951, 0.0954, 0.9178, 0.1315],
        [0.8645, 0.5919, 0.4995, 0.3378],
        [0.0279, 0.3090, 0.3559, 0.6315]])

In [22]:
print(some_torch)
print('------------------------------------------')
print(f"data type of tensor : ,{some_torch.dtype}")
print('------------------------------------------')
print(f"data shape of tensor : ,{some_torch.shape}")
print('------------------------------------------')
print(f"device tensor is : , {some_torch.device}")

tensor([[0.5951, 0.0954, 0.9178, 0.1315],
        [0.8645, 0.5919, 0.4995, 0.3378],
        [0.0279, 0.3090, 0.3559, 0.6315]])
------------------------------------------
data type of tensor : ,torch.float32
------------------------------------------
data shape of tensor : ,torch.Size([3, 4])
------------------------------------------
device tensor is : , cpu


In [25]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cpu')

In [26]:
tensor = torch.tensor([1,2,3])
tensor+100

tensor([101, 102, 103])

In [27]:
tensor * 10

tensor([10, 20, 30])

In [28]:
tensor

tensor([1, 2, 3])

In [29]:
tensor - 10

tensor([-9, -8, -7])

In [30]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [31]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [32]:
torch.sub(tensor,10)

tensor([-9, -8, -7])

In [33]:
print(tensor ,'*',tensor)
print(f'equals : {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
equals : tensor([1, 4, 9])


In [34]:
torch.matmul(tensor,tensor)

tensor(14)

In [154]:
value = 0
for i in range(len(tensor)) :
    value += tensor[i] * tensor[i]
print(value)

tensor(14)


In [155]:
torch.matmul(tensor,tensor)

tensor(14)

In [88]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.4613, 0.7197],
        [0.7600, 1.4726]])

# check math

## https://www.mathsisfun.com/index.ht


In [90]:
print(f"mostafa : {tensor}")

mostafa : tensor([1, 2, 3])


In [42]:
x = torch.arange(0,100,10)
x.dtype

torch.int64

In [43]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [44]:
torch.min(x)

tensor(0)

In [45]:
torch.max(x)

tensor(90)

In [46]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [47]:
x.sum(),torch.sum(x)

(tensor(450), tensor(450))

In [48]:
torch.argmin(x),x.argmin()

(tensor(0), tensor(0))

In [49]:
torch.argmax(x),x.argmax()

(tensor(9), tensor(9))

In [50]:
import torch
x = torch.arange(1.0,9.0)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

In [51]:
x_reshaped = x.reshape(1,8)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [52]:
z = x.view(1,8)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [53]:
z[:,0] = 5
z

tensor([[5., 2., 3., 4., 5., 6., 7., 8.]])

In [54]:
x_stacked = torch.stack([x,x,x,x],out=None)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8.],
        [5., 2., 3., 4., 5., 6., 7., 8.],
        [5., 2., 3., 4., 5., 6., 7., 8.],
        [5., 2., 3., 4., 5., 6., 7., 8.]])

In [55]:
x

tensor([5., 2., 3., 4., 5., 6., 7., 8.])

In [56]:
torch.squeeze(x)

tensor([5., 2., 3., 4., 5., 6., 7., 8.])

In [57]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8.]])

In [58]:
x_reshaped.shape

torch.Size([1, 8])

In [59]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8.])

In [60]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8.]])

In [61]:
x_reshaped.shape

torch.Size([1, 8])

In [62]:
squeez = x_reshaped.squeeze()

In [63]:
unsqueez = squeez.unsqueeze(dim=0)

In [64]:
unsqueez.shape

torch.Size([1, 8])

In [65]:
x = torch.randn([2,3,5])
x.size()

torch.Size([2, 3, 5])

In [66]:
torch.permute(x,(2,0,1)).size()

torch.Size([5, 2, 3])

In [67]:
x_orignal = torch.rand(size =(224,232,3))
x_permuted = x_orignal.permute(2,0,1)
print(f"prev shape {x_orignal.shape}")
print(f"new shape {x_permuted.shape}")

prev shape torch.Size([224, 232, 3])
new shape torch.Size([3, 224, 232])


In [68]:
x_orignal#[1,0,0]

tensor([[[0.1889, 0.0754, 0.3764],
         [0.4494, 0.0228, 0.2218],
         [0.3011, 0.1721, 0.3715],
         ...,
         [0.4170, 0.6246, 0.6385],
         [0.3101, 0.1307, 0.9869],
         [0.7718, 0.0218, 0.5259]],

        [[0.2099, 0.8937, 0.0610],
         [0.4406, 0.6640, 0.7813],
         [0.6583, 0.2629, 0.9619],
         ...,
         [0.8542, 0.6190, 0.5429],
         [0.1745, 0.5731, 0.7857],
         [0.2762, 0.7122, 0.2620]],

        [[0.7883, 0.5162, 0.9593],
         [0.1211, 0.8523, 0.7099],
         [0.9803, 0.7567, 0.9874],
         ...,
         [0.1213, 0.1337, 0.4442],
         [0.5766, 0.4300, 0.5713],
         [0.9718, 0.2909, 0.8926]],

        ...,

        [[0.5104, 0.6530, 0.1411],
         [0.3301, 0.2968, 0.8905],
         [0.7889, 0.3315, 0.5176],
         ...,
         [0.9123, 0.7551, 0.6069],
         [0.4934, 0.7481, 0.8837],
         [0.5408, 0.9513, 0.5896]],

        [[0.0264, 0.3857, 0.9580],
         [0.7690, 0.3759, 0.5267],
         [0.

In [74]:
x = torch.arange(1,10).reshape(1,3,3)

In [75]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [76]:
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [269]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [77]:
x[0][0]

tensor([1, 2, 3])

In [78]:
x[0][0]

tensor([1, 2, 3])

In [278]:
x[0][2][0]

tensor(7)

In [280]:
x[:,0]

tensor([[1, 2, 3]])

In [281]:
x[:,:,1]

tensor([[2, 5, 8]])

In [282]:
x[:,1,1]

tensor([5])

In [283]:
x[0,0,:]

tensor([1, 2, 3])

In [284]:
x[0,2,2]

tensor(9)

In [287]:
x[:,:,2]

tensor([[3, 6, 9]])

In [289]:
x[0][2][1]

tensor(8)

In [296]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [299]:
x[0][2][0]

tensor(7)

In [79]:
import torch 
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [80]:
array.dtype

dtype('float64')

In [81]:
tensor.dtype

torch.float32

In [82]:
torch.arange(1.,4.).dtype

torch.float32

In [83]:
array  += array

In [84]:
a = torch.Tensor([1,2,3,4,5,6,7,8,9])
a

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [85]:
tensor

tensor([1., 2., 3., 4., 5., 6., 7.])

In [86]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [87]:
import torch
random_tensor_a = torch.rand(3,4)
random_tensor_b = torch.rand(3,4)
print(random_tensor_a),print('\n'),print(random_tensor_b)
random_tensor_a == random_tensor_b

tensor([[0.5222, 0.4480, 0.5277, 0.8162],
        [0.3761, 0.5560, 0.4868, 0.9646],
        [0.7972, 0.4009, 0.4593, 0.7249]])


tensor([[0.0997, 0.3496, 0.4988, 0.4818],
        [0.0239, 0.4030, 0.6952, 0.9323],
        [0.8895, 0.8133, 0.9113, 0.2051]])


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [88]:
import torch
random_seed = 1
torch.manual_seed(random_seed)

random_tensor_a = torch.rand(4,3)
#torch.manual_seed(random_seed)

random_tensor_b = torch.rand(4,3)

print(random_tensor_a)
print('\n')
print(random_tensor_b)
print('\n')
print(random_tensor_a == random_tensor_b)

tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999],
        [0.3971, 0.7544, 0.5695],
        [0.4388, 0.6387, 0.5247]])


tensor([[0.6826, 0.3051, 0.4635],
        [0.4550, 0.5725, 0.4980],
        [0.9371, 0.6556, 0.3138],
        [0.1980, 0.4162, 0.2843]])


tensor([[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]])


In [89]:
import torch
tensor = torch.tensor([1,2,3])
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


# 2. Create a random tensor with shape (7, 7).

In [4]:
import torch
x = torch.rand(7,7)
x,x.shape

(tensor([[0.2984, 0.9709, 0.8785, 0.3056, 0.4223, 0.2905, 0.9382],
         [0.7975, 0.7890, 0.6357, 0.2176, 0.2407, 0.7492, 0.8897],
         [0.3608, 0.5032, 0.4698, 0.1668, 0.2368, 0.5342, 0.3060],
         [0.6857, 0.9245, 0.9792, 0.1032, 0.4550, 0.0279, 0.2845],
         [0.4314, 0.6450, 0.8896, 0.5289, 0.8618, 0.3114, 0.3670],
         [0.4301, 0.0430, 0.9640, 0.9847, 0.0205, 0.7359, 0.5139],
         [0.5751, 0.5663, 0.5326, 0.2924, 0.4576, 0.5270, 0.5400]]),
 torch.Size([7, 7]))

# 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [9]:
y = torch.rand(1,7)
z = torch.matmul(x,y.T)
z

tensor([[1.6158],
        [1.5205],
        [0.9341],
        [1.4892],
        [1.8365],
        [1.5232],
        [1.3757]])

# 4. Set the random seed to 0 and do 2 & 3 over again.

In [16]:
torch.manual_seed(0)
x = torch.rand(size =(7,7))
y = torch.rand(size =(1,7))

z = torch.matmul(x,y.T)
z ,z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

# 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [18]:
torch.cuda.manual_seed(1234)

In [20]:
torch.cuda

<module 'torch.cuda' from 'C:\\Users\\Mostafa\\anaconda3\\lib\\site-packages\\torch\\cuda\\__init__.py'>

# 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like

In [ ]:
device = 'cude' if torch.cuda.is_available else ''

In [26]:
torch.cuda.manual_seed(1234)
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
tensor_a = torch.rand(size =(2,3)).to(device)
tensor_B = torch.rand(size =(2,3)).to(device)
tensor_a,tensor_B

Device: cpu


(tensor([[0.5414, 0.6419, 0.2976],
         [0.7077, 0.4189, 0.0655]]),
 tensor([[0.8839, 0.8083, 0.7528],
         [0.8988, 0.6839, 0.7658]]))

# 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [28]:
tensor_c = torch.matmul(tensor_a,tensor_B.T)
tensor_c,tensor_c.T

(tensor([[1.2214, 1.1535],
         [1.0134, 0.9727]]),
 tensor([[1.2214, 1.0134],
         [1.1535, 0.9727]]))

# 8. Find the maximum and minimum values of the output of 7.

In [31]:
v = torch.max(tensor_c)
v

tensor(1.2214)

In [32]:
torch.min(tensor_c)

tensor(0.9727)

# Find the maximum and minimum index values of the output of 7

In [33]:
torch.argmax(tensor_c)

tensor(0)

In [34]:
torch.argmin(tensor_c)

tensor(3)

# 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [42]:
torch.manual_seed(7)
rand_tensor = torch.rand(size =(1,1,1,10))
new_tensor = torch.squeeze(rand_tensor)
new_tensor.shape

torch.Size([10])

In [47]:
print(rand_tensor)
print('......')
print(rand_tensor.shape)
print('\n')
print(new_tensor)
print('....')
print(new_tensor.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
......
torch.Size([1, 1, 1, 10])


tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
....
torch.Size([10])
